### ISSUE TITLE
Add support for choosing stations with the same name

### ISSUE THREAD

**Issue by EricIO** [Mousaka/sl-departures-in-terminal#1]
I want to query the times for "Universitetet (Roslagsbanan)" but only get results for "Universitetet (Tunnelbana och Bussar)". Maybe add functionality to be able to choose different stations with the same name.

**Comment by Mousaka** [comment]
:light_rail: 63ba2cc80d95e7ddb41d12d63edb8cb3c5795fdc solved in this commit. Thanks for the issue ;)
